### ISSUE TITLE
Socket error after restarting a container of newer versions of mosquitto

### ISSUE THREAD

**Issue by 0x0range** [thelebster/example-mosquitto-simple-auth-docker#3]
There is an issue with newer Versions of the mosquitto image. If I change the dockerfile to the newest version of the image:`FROM eclipse-mosquitto:1.6.9` everything works fine first. After I restart the container I get the following error message in the log file when I try to connect to the server. 

> eclipse-mosquitto | 1584471840: New connection from 172.22.0.1 on port 1883.
eclipse-mosquitto | 1584471840: Socket error on client <unknown>, disconnecting.

This only happens after the container stopped once or eg. the server restarts. I dont know if there is an issue on my side because I am not that experienced on docker or if it has to be with the newer versions of mosquitto. Here are the steps to repdroduce it. Maybe someone can find the issue i faced.

- Exchange the Dockerfile eclipse-mosquitto version to the newest version in my case `1.6.9`:
- `docker-compose build`
- `docker-compose up -d`
- To break it execute `docker-compose restart`

**Comment by tonyldo** [comment]
I have this issue too .... a try everything to discovery what happened with no success. You need to remove all container and up it again. if you stop the container and start again you will see the erro of sockect (0,5)

**Comment by thelebster** [comment]
I have run Mosquitto 1.6.12 and could not reproduce this issue. Could you provide more details? Do you use a right credentials?

**Comment by thelebster** [comment]
I have also made some improvements to support Mosquitto 2.x, like replacing 'port' to 'listener' and preparing directory to store pid file.
