### ISSUE TITLE
logs permissions issue

### ISSUE THREAD

**Issue by jaimemrjm** [thelebster/example-mosquitto-simple-auth-docker#4]
Note that will get an error like this with the current configuration:
`Error: Unable to open log file /mosquitto/log/mosquitto.log for writing.`

It's required to execute `chown 1883:1883 ./log` in the host to fix the issue. Check:
https://github.com/eclipse/mosquitto/issues/1078#issuecomment-465151208

**Comment by thelebster** [comment]
@jaimemrjm, thanks for the message, the issue should be fixed by [commit](https://github.com/thelebster/example-mosquitto-simple-auth-docker/commit/aa20ecb52742b26be9cb8f22c9076c6fce2eade0).
